### ISSUE TITLE
LaTeX bug

### ISSUE THREAD

**Issue by hturner** [forwards/fwdbrand#11]
I get `LaTeX Error: Command \nobreakspace unavailable in encoding T1` when running the example code.

This is with MikTeX 2.9, I think I have a full installation, or it should install packages on the fly.

**Comment by maelle** [comment]
I couldn't reproduce the bug on Appveyor. 😢

**Comment by hturner** [comment]
This is caused by using `"Dr. Marlin Wilderman"` as a name in the example - at some point a non-breaking space is added so this becomes `Dr.~Marlin Wilderman` and XeLaTeX complains about this (seems a known issue, see e.g. https://tex.stackexchange.com/q/66949/21118). Not sure how best to fix - the package should be able to handle a case like this properly.

**Comment by maelle** [comment]
I think the breaking space here appears due to punctuation but am not sure yet it should be removed in general or for punctuation. Agree that it needs to be solved because of e.g. the workshop content.

**Comment by maelle** [comment]
@hturner I've just pushed an update, could you please tell me if it solves the problem for you?

**Comment by maelle** [comment]
mmmh too bad it broke the Travis build, am going to remove it.

Can you remind me what TeX version you're using? I'm hoping you have a very old XeLaTeX version 😉

**Comment by maelle** [comment]
Apart from blaming your TeX version, am a bit stuck.

**Comment by hturner** [comment]
Seems you were right to blame my TeX version. Since my MikTeX was 2-3 years old, I reinstalled it and I can now run the example code producing both PDFs.
