### ISSUE TITLE
All arguments to be passed on to `render` from `create_workshop_certificate`

### ISSUE THREAD

**Issue by hturner** [forwards/fwdbrand#13]
E.g. it would be useful to pass on `clean = FALSE` so that if there is just a problem with the LaTeX compilation that can be trouble-shooted using the .tex file.

Similarly being able to keep the `.md` or `.tex` would allow quick hacks in the case of bugs/missing features, as a short-term fix.

**Comment by maelle** [comment]
Having clean=FALSE only keeps intermediary .md files that are less useful.

For now I'll only add the keep_tex param. keep_tex corresponds to what you need but it's in params (named list) passed to rmarkdown::render, and a default value needs to be defined in the Rmd template, so I can't just have "...".
