### ISSUE TITLE
Prettify certificates

### ISSUE THREAD

**Issue by maelle** [forwards/fwdbrand#16]
From @hturner in #6  "It would be nice to have a thin multi-colour border on the page (like the hexsticker border but with a print margin round the outside). This may be fiddly though."

**Comment by maelle** [comment]
I couldn't find anything relevant and won't have time to experiment with TeX that much, so I'll implement a grey frame, and then someone could improve on it later.

**Comment by hturner** [comment]
Closed by 8052669c298edb27d22fe7d02aedf9cc79f31ec6
