### ISSUE TITLE
De-pixelize logo

### ISSUE THREAD

**Issue by maelle** [forwards/fwdbrand#20]
From my looking at https://github.com/forwards/fwdbrand/blob/master/inst/assets-scripts/create_hex_sticker.R the culprit is the PNG, will try starting from a better PNG.

cc @hturner

**Comment by maelle** [comment]
Hmmm not sure _how_ actually. I don't remember how I created the PNG but anyway if I do

```r
magick::image_read_svg("inst/extdata/assets/forwards.svg")
```
I obtain an image with poor resolution.

**Comment by hturner** [comment]
`magick::image_read_svg` is using **rsvg** to create a bitmap. So you might be able to get round this by reading in with excessively large width and height (e.g. 2000 x 2000 pixels), so when later scaled to required size, resolution is much better? Stickermule recommend it to be at least 300 pixels per inch: https://www.stickermule.com/uk/support/file-formats.

But it would be nice if we could produce it in vector format. I think the sticking point with the original logo code was the **grConvert** package not running on Windows. Perhaps this is solved with https://github.com/richfitz/vectoR?

**Comment by maelle** [comment]
I can try reading it in with higher values later this week-end but I won't have time exploring the other options, sorry.

**Comment by maelle** [comment]
cf https://github.com/GuangchuangYu/hexSticker/issues/37

**Comment by hturner** [comment]
An alternative solution might be to use ggplot with a gradient fill polygon (https://www.uv.es/mimica/Rblog/polygon.html) + white polygon + SVG logo with transparent background.   We can then save as svg.

**Comment by hturner** [comment]
Increasing resolution worked to de-pixelise the logo. I will open a new issue for creating the hexsticker directly as SVG as a longer-term wish.
