### ISSUE TITLE
make it a package?

### ISSUE THREAD

**Issue by maelle** [forwards/fwdbrand#5]
Code creating stuff would be in data-raw, files in inst/extdata, and this way the RMarkdown template(s) might be easier to store... not sure what's best.

**Comment by hturner** [comment]
This seems a good way to distribute the R markdown templates. Thinking ahead to the workshop certificate template (issue to follow) it would be nice to have a R function where you just input the relevant names to render the certificate.

Minor suggestion: As none of this has to do with data, perhaps use asset-scripts and inst/templates to store.

**Comment by maelle** [comment]
It is now a package :tada:
