### ISSUE TITLE
Creating a package development workshop certificate template

### ISSUE THREAD

**Issue by hturner** [forwards/fwdbrand#6]
This could be done a couple of ways as I outline below. The first is simpler and easier to keep up-to-date, but the second gives more details about what the workshop is about. I'm not sure which is best. 

I have examples from other workshops that could give an idea of the layout, that I will share directly.

Ideally this would be implemented as a parameterised R markdown or similar, so we can easily generate certificates for participants.

## Option 1 [Landscape, Forwards logo in header or possibly as background watermark]

CERTIFICATE OF PARTICIPATION

This certificate is awarded to 

[Full Name]

for completing the R Package Development Workshop, a total of 6 hours instruction with guided computer programming exercises.

[Date]
Date

[Space for signature]
[Full name of certifying person]
[Position of certifying person (e.g. Workshop Tutor or Forwards Teaching Team Member or similar as appropriate)]

Forwards: the R Foundation taskforce on women and other under-represented groups (https://forwards.github.io/)

## Option 2 [Portrait, Forwards logo in header]

CERTIFICATE

[Full Name]

has participated in the 

R Package Development Workshop

date

Workshop contents:

* Making code into an R package
* Collaborative coding with GitHub
* Writing a vignette or an article
* Building a package webpage
* Submitting a package to CRAN

[Space for signature]
[Full name of certifying person]
[Position of certifying person (e.g. Workshop Tutor or Forwards Teaching Team Member or similar as appropriate)]

Forwards: the R Foundation taskforce on women and other under-represented groups (https://forwards.github.io/)

**Comment by maelle** [comment]
Is the font Open Sans?

**Comment by maelle** [comment]
Note to self: use charlatan to create fake names

**Comment by maelle** [comment]
Other question for @hturner: does Forwards have an address? It'd make it look more legit?

**Comment by hturner** [comment]
I don't mind about the font. Forwards doesn't have an address. If you think it helps you could point to the R Foundation details https://www.r-project.org/foundation/ (there still isn't an address there mind).

**Comment by maelle** [comment]
I thought it was Open Sans because that's the logo font :wink:

I guess it's fine without address then! I'm shocked that even the R foundation status doesn't state an address 😀

**Comment by maelle** [comment]
Notes

* See https://github.com/hrbrmstr/markdowntemplates structure

* The workshop content could be expected as an input path, and the workshop leader would write them as .md or so

* The package name should probably be more specific

* The documentation of the template should show an example of using `render` with parameters.

* Pdf seems to be the most natural output format for such a certificate but the docs should mention [tinytex](https://yihui.name/tinytex/) for ease of installation.

* Changing the font is more complicated than I expected. I am currently installing the mathspec TeX package that didn't seem to be installed yet. I am worried that such details will make this template less usable (because not everyone likes/is used to mess up with LaTeX). That said missing packages is one thing tinytex helps with 🎊

**Comment by hturner** [comment]
Have you considered using the showtext R package? This has helped me before when I needed extra fonts but did not have much control over the installation (working on a server).

**Comment by maelle** [comment]
will have a look, thanks! I've used it in the past. Yesterday I stopped working on this after installing `tinytex`, will resume work this week hopefully.

**Comment by maelle** [comment]
Am installing https://fonts.google.com/specimen/Open+Sans?selection.family=Open+Sans because it was the font used in the logo.

**Comment by maelle** [comment]
It actually seems more promising to install the opensans _package_ http://www.tug.dk/FontCatalogue/opensans/

**Comment by maelle** [comment]
Now the next steps will be to:

* Make it look good (including use of the logo!)

* Document it including writing an example of generating a series of certificates based on a `charlatan`-generated list of names, and with a custom defined workshop content.

**Comment by maelle** [comment]
> I have examples from other workshops that could give an idea of the layout, that I will share directly.

@hturner could you please try the current function to see how the background watermark looks like and tell me how much smaller + how much more transparent you want it?

Could you also send me the layout examples?

I think the function is now ok but that certificate needs to get prettier. Forwards info could be a footer, right now it is in the middle of the certificate.

**Comment by hturner** [comment]
I sent the layout examples to you on Forwards slack.

**Comment by maelle** [comment]
For the footer I should use fancyhdr 🤔

**Comment by maelle** [comment]
Am trying to use that but it doesn't work yet. 😿

**Comment by maelle** [comment]
Apart from the absence of the footer @hturner what are easy fixes for this template?
[package_development_workshop_01.pdf](https://github.com/forwards/fwdbrand/files/2137045/package_development_workshop_01.pdf)

**Comment by hturner** [comment]
These are hopefully easy fixes that I think will improve the result:
- [x] Larger font for main content (possibly also title/footer). Content should fill most of page but need to be careful as I suppose if it overlaps with dark part of logo/FORWARDS it may not look so good.
- [x] Centre all content
- [x] Add Forwards url to footer
- [x] Allow a print margin (i.e. reduce size of background logo)
- [x] Enable page size to be customized (currently US letter)
- [x] Add optional location (e.g. name of university or conference where workshop was held)

It would be nice to have a thin multi-colour border on the page (like the hexsticker border but with a print margin round the outside). This may be fiddly though.

**Comment by maelle** [comment]
Am going to put the most difficult part in a separate nice-to-have issue and will work on the rest 😁

**Comment by maelle** [comment]
The fun is already starting, the URL is in the template but doesn't appear 😩

**Comment by maelle** [comment]
Note to self: the wallpaper TeX package doesn't have a margin option and changing the margins of the document doesn't affect the wallpaper so I'll just create and use a logo with white borders to solve the problem.

**Comment by maelle** [comment]
Remaining are font size (I tested two solutions with no success so fare) and page size (haven't done anything yet)

**Comment by maelle** [comment]
Am trying to increase text size a bit but to make it really bigger everywhere, I might need a custom doc class (not going to happen 🙈 ) or to use \Large etc differently than now (so not using \normalsize at all).

**Comment by maelle** [comment]
Note to self: when adding the option for paper size, use pdftools to test the behavior if possible. Cf https://github.com/ropensci/pdftools/issues/41

**Comment by hturner** [comment]
Final fixes on TODO list implemented in 8052669c298edb27d22fe7d02aedf9cc79f31ec6
