### ISSUE TITLE
Signing certificates

### ISSUE THREAD

**Issue by maelle** [forwards/fwdbrand#9]
@hturner would you expect the certificates to be signed by hand or not? If not, I'm wondering about how to make it easier (supply your signature as ??? electronic format and have it added automatically to all certificates)

**Comment by hturner** [comment]
Short-term: yes, by hand.

Long-term: it would be nice to be able to add a signature as a vector graphic. `potrace` seems to be the tool for creating such a graphic file (does not need to be part of package, only the end result is needed to add to the certificate). See e.g. https://tex.stackexchange.com/a/32940/21118.

**Comment by maelle** [comment]
And do you think universities&co will see the certificate as valid when signed this way?

**Comment by hturner** [comment]
I don't think we need to do anything special here - people can choose to sign by hand or add an electronic signature e.g. using Adobe Acrobat Reader Fill & Sign feature.
